### ISSUE TITLE
Proposal: add historical initiatives & whitepapers from Water & Music Report

### ISSUE THREAD

**Issue by almndbtr** [lucasgonze/Music-NFT-Metadata-Proposal#1]
## Summary

[Water & Music](https://www.waterandmusic.com/) is a newsletter and research DAO building the innovator’s guide to the music business.

They published these two articles with some pretty incredible resources for music metadata:

- https://www.waterandmusic.com/defining-music-nft-ownership-from-the-digital-to-the-analog-world/
- https://www.waterandmusic.com/the-state-of-music-web3-tools-for-artists/

I propose that each respective resource be included in the README (of course, citing attribution back to Water & Music for their work):

- [#MTFLabs: Blockchain](https://cris.brighton.ac.uk/ws/portalfiles/portal/486119/Blockchain-Whitepaper.pdf%092016) (2016)
- [Watermarking technologies and blockchain in the music industry](https://www.digimarc.com/docs/default-source/digimarc-resources/whitepaper-blockchain-in-music-industry.pdf?sfvrsn=2) (Digimarc, 2017)
- [Towards an Open and Scalable Music Metadata Layer](https://arxiv.org/pdf/1911.08278.pdf) (Berklee/MIT, 2019)
- [Fair Music: Transparency and Payment Flows in the Music Industry](https://creativepassport.net/wp-content/uploads/2019/10/Fair-Music-Transparency-and-Payment-Flows-in-the-Music-Industry.pdf) (Rethink Music, 2019)
- [The Genesis of Music3](https://gateway.pinata.cloud/ipfs/QmX9tuaHepxwaTwTU5TnWDksWNSSm2JWNncc2avLABTavc) (MODA DAO, 2021)
- [A better music NFT metadata standard](https://mintsongs.notion.site/mintsongs/A-better-Music-NFT-metadata-standard-260506f3a5b342c6b0c893892f37e711) (Garrett Hughes/crowdsourced, 2021)

cc: @lucasgonze for triage! Happy to cut a PR for this, if it's welcome! 🙇‍♂️

**Comment by lucasgonze** [comment]
This is valuable. Would you want to cut a PR with a new "References" section?

I believe the https://mintsongs.notion.site/mintsongs/A-better-music-token-metadata-standard-260506f3a5b342c6b0c893892f37e711 link is a duplicate of one already in the README, though with a different domain name.

**Comment by lucasgonze** [comment]
I merged them into the README:
https://github.com/lucasgonze/Music-NFT-Metadata-Proposal/blob/main/README.md

That's more ragged than necessary. When I get time I'll review and condense all those materials.

**Comment by almndbtr** [comment]
@lucasgonze Ah, thank you! I was going to volunteer but you beat me to the punch. 😉Next time, then. I’ll close this out since it’s already incorporated! 🚀

**Comment by lucasgonze** [comment]
You inspired me to redefine this repo as a place for discussion. From now on https://github.com/lucasgonze/Music-NFT-Metadata-Proposal/discussions/ is the point of it.
